export const SEARCH_USER_DATA = 'SEARCH_USER_DATA';
export const SEARCH_USER_DATA_SUCCESS = 'SEARCH_USER_DATA_SUCCESS';
export const SEARCH_USER_REPOSITORIES_SUCCESS =
  'SEARCH_USER_REPOSITORIES_SUCCESS';
export const SEARCH_USER_DATA_FAILURE = 'SEARCH_USER_DATA_FAILURE';
